### ISSUE TITLE
What happen with Laracogs?

### ISSUE THREAD

**Issue by MatheusRV** [GrafiteInc/Builder#188]
ps. Edit github website link still laracogs

**Comment by shabaz-ejaz** [comment]
Yes I think its really bad to completely faze it out. If people are actively working with Laracogs we need to documentation readily available. It's like they brushed it under the carpet without a single mention.

**Comment by mlantz** [comment]
We had to undergo an abrupt name change and package name changes in order to maintain the codebase. All components were brought over to the new Grafite brand. In this case Laracogs is now Grafite Builder. There were mentions of this in the chat channels in Gitter as well as mentions in the Github profile name the day the packages moved over, as well as day by day feedback on the state of changes while new documentation sites were being built etc. The laracogs domain now links to the proper docs etc. Nothing was brushed under carpets it has been a complex process to go through. Thanks @MatheusRV for the info

**Comment by shabaz-ejaz** [comment]
@mlantz The day the packages moved over? But it's too late by then. There was no way for developers to know about this change unless they purposefully went onto those channels you talk about.  Why was there an 'abrupt' name change? Also why do you call it 'abrupt?'

**Comment by CaddyDz** [comment]
I use Laracogs for every "less than a week" quick project
The installer wasn't working, I sent a PR and the entire repo was deleted without notice
Am not complaining, but I really think there should be some community maintainers with write access to the repos
It's just too much work for a single person to handle
